Sprint-1 features
eclipsesource/theia-tutorial-extension pull request #3
Opened 2021-01-03 07:40 UTC by buraktomruk

2021-01-03 07:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/theia-tutorial-extension?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/theia-tutorial-extension?pullRequest=3) before we can accept your contribution.<br/>**1** out of **5** committers have signed the CLA.<br/><br/>:white_check_mark: LukasBoll<br/>:x: lukasBoll<br/>:x: minrows<br/>:x: buraktomruk<br/>:x: max-elia<br/><hr/>**lukasBoll** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/theia-tutorial-extension?pullRequest=3) it.</sub>

2021-01-14 09:47 UTC, eneufeld requested changes
I stopped for now, 
please check all files for:
- missing types
- missing headers
- console.log and remove where it is not needed
- es-lint-disable-next-line 
- remove commented out code if it is not needed
- Use material component where possible instead of writing a lot of custom css
- do not wrap in unnecessary div elements
- use (fat) arraw function definitions instead of functions : `const foo = () => {}` instead of `function foo () {}`
- update readme to include some description about this project

2021-01-14 09:47 UTC, eneufeld commented on react-app/public/manifest.json
> +  "short_name": "React App",
Adapt names accordingly

2021-01-14 09:47 UTC, eneufeld commented on react-app/public/index.html
> +    <title>React App</title>
Adapt title

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/App.tsx
> +            //@ts-ignore
why?

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/App.tsx
> +  const [tutorials, setTutorials] = useState<Array<any>>([]);
use types

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/App.tsx
> +  function createTutorialList() {
I would suggest to use `const createTutorialList = () => {...}` format instead. This way you won't get problems with `this` as the scope stays correct.

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/App.tsx
> +        ? <p><header className="App-header">
why use paragraphs instead of divs?
I would suggest to move this into a small helper component, so that it is easier to read the code

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/components/Exercise.tsx
> +// eslint-disable-next-line @typescript-eslint/naming-convention
why?

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/components/Exercise.tsx
> +  exercise: any
add type

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/components/Exercise.tsx
> +export const Exercise = (props: ExerciseProps) => {
deconstruct the prop directly to have access to the `exercise`

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/components/Exercise.tsx
> +  console.log(props);
needed?

2021-01-14 09:47 UTC, eneufeld commented on react-app/src/components/Exercise.tsx
> +const Hint = (props: any) => {
type missing

2021-01-20 14:17 UTC, buraktomruk commented
Requested changes will be in pull request of sprint-2.

2021-01-20 14:17 UTC, closed without merging