Sprint-1 and Sprint-2 features
eclipsesource/theia-tutorial-extension pull request #4
Opened 2021-01-21 11:12 UTC by buraktomruk

Requested changes for sprint-1 are also added in this PR.

2021-01-21 11:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/eclipsesource/theia-tutorial-extension?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/eclipsesource/theia-tutorial-extension?pullRequest=4) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: max-elia<br/>:white_check_mark: buraktomruk<br/>:white_check_mark: minrows<br/>:x: lukasBoll<br/><hr/>**lukasBoll** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/eclipsesource/theia-tutorial-extension?pullRequest=4) it.</sub>

2021-01-22 19:20 UTC, eneufeld requested changes
Is the `helloworld` file needed?
I would that you suggest setting up the repo with lint rules and formatting as defined here: https://github.com/sdirix/react-app-starter/ so configure lint and prettier
This will increase the readability a lot.
Please also try to create small components, they are easier to refactor and understand

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/App.test.tsx
> +it('renders without crashing', () => {
it probably makes sense to add some tests?

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/App.tsx
> +  const createTutorialList = () => {
if you want to pull this out for readability, add a new functional component, it is cleaner

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/App.tsx
> +
remove unneeded empty lines

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/Command.tsx
> +        margin: "10px 10px 10px 10px",
why use material ui if you completely resyle the button?

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/StepperComponent.tsx
> +const useStyles = makeStyles((theme: Theme) =>
I suggest to either completely get rid of material ui or at least do a custom theme were you redefine everything

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/StepperComponent.tsx
> +const StepperComponent = (props: StepperComponentProps) => {
You should split the rendering in some sub components, it is hard to understand what is going on

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/TestFeedbackDialog.tsx
> +        return <div><Grid
if you just need an element to wrap, you can use: `<>` instead

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/TutorialOverview.tsx
> +                <Stepper orientation="vertical" style={{backgroundColor: "transparent"}}>
Pull out as component

2021-01-22 19:20 UTC, eneufeld commented on react-app/src/components/TutorialOverview.tsx
> +const TutorialOverview = (props: TutorialOverviewProps) => {
you can deconstruct in line:
```suggestion
const TutorialOverview = ({tutorial}:TutorialOverviewProps) => {
```

2021-01-22 19:20 UTC, eneufeld commented on src/Commands/AddImportsCommand.ts
> +    let filepath = path.join(workspaceFolder, autoImportData.automaticImport.path);
why `let`? can't we use const?

2021-01-22 19:20 UTC, eneufeld commented on src/Commands/AddImportsCommand.ts
> +    let content = fs.readFileSync(filepath);
same as above

2021-01-22 19:20 UTC, eneufeld commented on src/Commands/CloneRepoCommand.ts
> +const CLONEREPOCOMMAND: vscode.Disposable = vscode.commands.registerCommand('theiatutorialextension.cloneRepo', () => {
why is it all uppercase is this some kind of convention for commands?

2021-02-02 11:31 UTC, eneufeld commented
So overall the commit is ok, I suggest to fix at least the formatting by configuring prettier and eslint .
Furthermore it would be great if you could check that all files have headers (should be handled by eslint ideally). 
After this 2 points this PR can be merged so that an initial version is in.

After that some more cleanup will be needed:
- there are some `let` uses where you could use `const` imho
- split react components to smaller ones so that the readability is improved
- use react components instead of functions to create dom elements 

On the long run you should discuss whether material-ui is the best choice here.

2021-02-02 14:36 UTC, eneufeld commented
Ok I talked with Jonas, so I suggest to do the following:
- check all files and add missing headers -> merge afterwards
- create individual issues for all open points
Thank you!

2021-02-09 10:35 UTC, eneufeld commented on src/Commands/LoadConfigCommand.ts
> +                if (tutorial.exercises[i].checkStartState == null && i !== 0) {
why replace the `===` with `==` ?

2021-02-09 10:42 UTC, eneufeld commented
Looks good overall. Please make sure to sign the eclipse eca.
Please fix missing headers, after that we can merge.
Please open issues for all open review comments.

2021-02-24 19:02 UTC, buraktomruk commented
The new PR is #6 I can close this

2021-02-24 19:02 UTC, closed without merging